# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme
title:                        南科大开源软件协会
search:                       true # true, false (default)
search_full_content:          true # true, false (default)
email:                        opensustech@outlook.com
description:                  南科大开源软件协会官网
url:                          "https://sustech-opensource.github.io"
baseurl:                      ""
github_username:              SUSTech-OpenSource
locale:                       "zh-CN"
markdown:                     kramdown
timezone:                     "Asia/Shanghai"
# name of github repository
repository:                   "SUSTech-OpenSource/SUSTech-OpenSource.github.io"
# Build settings      
theme:                        "minimal-mistakes-jekyll"
minimal_mistakes_skin:        "mint"
logo:                         "/assets/images/LOGO.png"
words_per_minute:             150
#include:                      ["_pages","_project","_news","_ideas"]

exclude:
  - ".jekyll-cache"
  - "Gemfile"
  - "Gemfile.lock"
  - "LICENSE"
  - "README.md"
  - "template/*"

footer:
  links:
    - label: "Github"
      icon:    "fab fa-fw fa-github"
      url:     "https://github.com/SUSTech-OpenSource"
    - label: "Bilibili"
      icon:    "fa fa-film"
      url:     "https://space.bilibili.com/1171066524"

author:
  name:         "SUSTech-OpenSource"
  avatar:       "/assets/images/LOGO.png"
  bio:          "南科大开源软件协会"
  location:     "SUSTech"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:opensustech@outlook.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/SUSTech-OpenSource"

paginate: null
paginate_path: null

permalink: /:categories/:year/:month/:title/
pagination:
  enabled: true
  per_page: 5
  permalink: "/:num/"
  title: ":title - :num/:max"
  limit: 0
  sort_field: "date"
  sort_reverse: true
  trail:
    before: 2
    after: 2
autopages:
  enabled: true
  categories:
    layouts: [ 'autopages.html' ]
    title: 'Category: :cat'
    permalink: '/category/:cat'
  collections:
    layouts: ['autopages.html']
    title: '最新内容'
    permalink: '/:coll'
  tags:
    layouts: [ 'autopages.html' ]
    title: 'Tag: :tag'
    permalink: '/tag/:tag'

collections:
  project:
    output: true
    permalink: /:collection/:year/:month/:title/
  pages:
    output: true
    permalink: /:collection/:path/
  news:
    output: true
    permalink: /:collection/:year/:month/:title/
  ideas:
    output: true
    permalink: /:collection/:year/:month/:title/

category_archive:
  type: jekyll-archives
  path: /categories/
tag_archive:
  type: jekyll-archives
  path: /tags/
# https://github.com/jekyll/jekyll-archives
jekyll-archives:
  enabled: [categories, tags]
  layout: archive-taxonomy
  layouts: {}
  permalinks:
    year: /year/:year/
    category: /categories/:name/
    tag: /tags/:name/


defaults:
  - scope:
      path: ""
    values:
      layout: single
      toc: true
      toc_sticky: true
      toc_label: 目录
      share: true
      related: true
      header:
        show_overlay_excerpt: false
  - scope:
      path: ""
      type: pages
    values:
      excerpt: false
      share: false
      related: false
      sidebar:
        nav: pages
  - scope:
      path: ""
      type: news
    values:
      author_profile: true
      show_date: true
      classes: ["news"]
  - scope:
      path: ""
      type: ideas
    values:
      author_profile: true
      show_date: true
      read_time: true
      toc: true
      toc_sticky: true
      toc_label: 目录
      share: true
      related: false
  - scope:
      path: ""
      type: project
    values:
      excerpt: false
      share: false
      related: false
      sidebar:
        nav: project